### PR TITLE
Image copyright information

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/153542#note-9

First draft of the component:
https://62713c57bcbdf4004a3d99b8-lfsakqvryi.chromatic.com/?path=/story/components-copyright--default

Ιmport in story showcase (Page Header):
https://62713c57bcbdf4004a3d99b8-lfsakqvryi.chromatic.com/?path=/story/components-page-header--default

Import in component showcase (Hero)
https://62713c57bcbdf4004a3d99b8-lfsakqvryi.chromatic.com/?path=/story/components-hero--default

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
