### PR TITLE
[R2] Mega Menu version 2

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/147802

https://62713c57bcbdf4004a3d99b8-oyzmlotedj.chromatic.com/?path=/story/layout-header--default

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@tarantilis  there is extra spacing when title button is active

**Review by ichim-david — CHANGES_REQUESTED** [review]
@tarantilis  see chat for details of strange title behavior

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Review by avoinea — APPROVED** [review]

**Pull request merged**
