### PR TITLE
[R3] Labeled icons

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/148413
https://62713c57bcbdf4004a3d99b8-ksanfrneht.chromatic.com/?path=/story/components-labeled-icons-download--default

### CODE REVIEW

**Comment by avoinea** [comment]
@eea-jenkins build all

**Comment by valentinab25** [comment]
@eea-jenkins build all

**Comment by valentinab25** [comment]
@eea-jenkins build all

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Review by avoinea — APPROVED** [review]

**Pull request merged**
