### PR TITLE
[R2] Card refactored as an [R3]

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/147791

Please merge with priority.

### CODE REVIEW

**Comment by g-stamatis** [comment]
Conflicts have been resolved keeping the files from develop.

**Comment by avoinea** [comment]
@g-stamatis This changes seems to affect also the timeline component.

timeline

**Comment by avoinea** [comment]
@g-stamatis Can you make the blue background with white text as a card `inverted` variation? And leave it with black text on white background as default?

I can't see the `inverted` option in semantic ui for Card, but you can check Table for it: https://react.semantic-ui.com/collections/table/

**Comment by avoinea** [comment]
@g-stamatis Also the `meta` text color should be adjusted:

meta-card

**Review by avoinea — CHANGES_REQUESTED** [review]
Please see my comments above.

**Comment by g-stamatis** [comment]
@avoinea issues have been addressed in the latest push.

.ui.card.inverted is now the default card

**Review by avoinea — APPROVED** [review]

**Pull request merged**
