### PR TITLE
[R2] Message

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/147797

https://62713c57bcbdf4004a3d99b8-xzqicbhvro.chromatic.com/?path=/story/components-message--default

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — CHANGES_REQUESTED** [review]
@g-stamatis add headers also to the message types not just the basic message within the storybook as they are empty and you can't set anything

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
