### PR TITLE
[R2] Statistic

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/147794

https://62713c57bcbdf4004a3d99b8-naxozktvby.chromatic.com/?path=/story/components-statistic--group

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by demarant** [comment]
Let's try to also get into this PR the "count up" animation that you can see on this article made by EEA some time ago
https://www.eea.europa.eu/themes/water/europes-seas-and-coasts/assessments/marine-litterwatch/briefing#about

It should be exposed in the control, and by default off with some options to configure it, e.g. animation speed.

if possible, please add other animations/transitions, if easy to add.

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@g-stamatis https://62713c57bcbdf4004a3d99b8-zwhfqvmqaa.chromatic.com/?path=/story/components-statistic--animation-group&args=valueVariation:primary;labelVariation:secondary;inverted:true 
For the animation group you should add the buttons from the Animation storybook since you give options
but you can't replay the animations after you've played with any of the options

**Comment by ichim-david** [comment]
https://62713c57bcbdf4004a3d99b8-zwhfqvmqaa.chromatic.com/?path=/story/components-statistic--animation&args=decimals:1;prefix:d;suffix:z;size:huge;horizontal:true&globals=backgrounds.grid:false
@g-stamatis  I see the following issues:
- when you are on mobile and you enable horizontal the value goes out of view when using a larger size
- the value is enlarged but what if there is a need to have also the subtext larger?
- Horizontal and inverted will push bring a bg color that looks bad without some padding in the content area

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Pull request merged**
