### PR TITLE
Cards - All variations - Accessibility fixes

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/152256?tab=time_entries

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Review by ichim-david — CHANGES_REQUESTED** [review]
See https://taskman.eionet.europa.eu/issues/152256#note-2
for details

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by avoinea** [comment]
@tarantilis The [carousel](https://62713c57bcbdf4004a3d99b8-edzpsspmdk.chromatic.com/?path=/story/components-card-default--carousel-cards) seems to be broken.

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by valentinab25** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
