### PR TITLE
[Docusaurus] Header and footer elements updates

### PR DESCRIPTION
**Pull request by g-stamatis**
Docusaurus https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-277/2/volto-eea-design-system/

No related ticket available.

Header and Footer anatomy updates in docusaurus.

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Review by ichim-david — COMMENTED** [review]
@g-stamatis please keep file naming consistent
footer_elements.png
headerElements.png
I think that the image file naming should be:
footer-elements.png
header-elements.png
or perhaps:
footer_elements.png
header_elements.png
for the double click whole words selection.

We need to have a standard of naming that is consistent,
I will request changes more after we come to an agreement.

**Review by ichim-david — CHANGES_REQUESTED** [review]
@g-stamatis we have a convention now,
lowercase-names-with-dashes.extension
so please rename the image names uploaded in this pull request

**Comment by g-stamatis** [comment]
@ichim-david are we talking about the two images in this PR only or all of them? I would suggest a separate PR if we are renaming them all, since it will require refactoring in many pages. There are approximately 150 image (png and svg) files in the design system, the vast majority of which do not follow the convention.

**Comment by ichim-david** [comment]
> @ichim-david are we talking about the two images in this PR only or all of them? I would suggest a separate PR if we are renaming them all, since it will require refactoring in many pages. There are approximately 150 image (png and svg) files in the design system, the vast majority of which do not follow the convention.
@g-stamatis just the files added in this pull request, I have similar comments for another pull request where you will modify the naming from the files touched by that pull request.

Then we will have another pull request that renames what's left

**Comment by ichim-david** [comment]
@g-stamatis I went ahead  and did the rename myself, merging work as such now

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
