### PR TITLE
268495 draft image

### PR DESCRIPTION
**Pull request by ichim-david**

### CODE REVIEW

**Comment by ichim-david** [comment]
@eea-jenkins build docusaurus

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build docusaurus

**Comment by ichim-david** [comment]
@eea-jenkins build story

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build docusaurus

**Comment by ichim-david** [comment]
@eea-jenkins build docusaurus

**Comment by ichim-david** [comment]
@eea-jenkins build docusaurus

**Review by avoinea — APPROVED** [review]

**Pull request merged**
