### PR TITLE
[R3] Related articles (sub component) 1/2

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/147641

### CODE REVIEW

**Comment by g-stamatis** [comment]
Please merge this one before the related-content

**Comment by g-stamatis** [comment]
[R3] Related articles (sub component)
https://taskman.eionet.europa.eu/issues/147641

**Comment by avoinea** [comment]
@g-stamatis See figma comments. This should be a grid with [Cards](https://eea.github.io/volto-kitkat-frontend/?path=/story/components-card--default) or [Items](https://eea.github.io/volto-kitkat-frontend/?path=/story/components-item--default-item)

Please update the Item component according to @demarant comments on figma homepage.

**Comment by g-stamatis** [comment]
Will be moved as a card variation.

**Comment by g-stamatis** [comment]
This is moved in card branch.

**Pull request closed without merging**
