### PR TITLE
Green colour/[Docusaurus] Logos page

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/154607
https://taskman.eionet.europa.eu/issues/153541

Docusaurus latest logo
https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-253/58/volto-eea-design-system/

Storybook latest logo
https://62713c57bcbdf4004a3d99b8-thuovweokd.chromatic.com/?path=/story/components-logo--logo

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — CHANGES_REQUESTED** [review]
@g-stamatis  the eea logo is missing from the showcase tab
https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-253/19/volto-eea-design-system/docs/webdev/Components/Logo/

**Comment by demarant** [comment]
@g-stamatis , @ichim-david 

here my feedback:
1) the logo displayed on the "usage tab" which display the margins https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-253/22/volto-eea-design-system/
is not the latest one as the svg. I therefore propose to remove that logo and replace with the SVG one, the 20px margin should not be part of the SVG, rather should be added by CSS when included on the site heade, this would give more flexibility to the frontend developer to accomondate any type of header. 

2) what about the logos variation used on dark background, I mean the logo with white-strokes and no color filling? these should also be part of the logo page. I think we should add it and explain where/when it is used.

**Review by ichim-david — CHANGES_REQUESTED** [review]
@g-stamatis  as talked about in tickets as well add also the inverted variants in the storybook and in docusaurus

**Comment by tarantilis** [comment]
@eea-jenkins build all

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Review by ichim-david — CHANGES_REQUESTED** [review]
@tarantilis @g-stamatis  I think that the thematic logos should be the same size
like the outputted version of the eea logo without all the extra spacing.

I also don't like the fact that the storybook logo only shows the eea logo
which when turned to inverted doesn't get the black background to make
the white logo visible

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build docusaurus

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build docusaurus

**Pull request merged**
