### PR TITLE
[Storybook][Docusaurus] Visited link colour

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/158905

Docusaurus: https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-278/9/volto-eea-design-system/
Storybook: https://62713c57bcbdf4004a3d99b8-brtyknpuck.chromatic.com/

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Review by ichim-david — CHANGES_REQUESTED** [review]
@g-stamatis as requested in the visited links pull request
https://github.com/eea/volto-eea-design-system/pull/277#issuecomment-1377560107
please rename the images for the logos to lowercase with dashes.

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Comment by g-stamatis** [comment]
@ichim-david Images found in use in the website/docs/webdev/md_components/static folder have been renamed using the new convention. Filenames of type colors1 were not renamed to colors-1. Please let me know if you want those renamed as well.

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
