### PR TITLE
Card updates 1/2

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/151148

https://62713c57bcbdf4004a3d99b8-awhomtnznz.chromatic.com/?path=/story/components-card-default--default

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by avoinea** [comment]
Using this branch our carrousel integration have some issues:

cards

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
Merged inside [Cards - All variations - Accessibility fixes](https://github.com/eea/volto-eea-design-system/pull/210 )
The requested changes were addressed in the new PR.

**Pull request closed without merging**
