### PR TITLE
[Accessibility] Firefox accessibility tab issues

### PR DESCRIPTION
**Pull request by tarantilis**
in progress, still checking

Mega menu:
https://62713c57bcbdf4004a3d99b8-exkrywpouk.chromatic.com/?path=/story/layout-header--default

Breadcrumbs:
https://62713c57bcbdf4004a3d99b8-exkrywpouk.chromatic.com/?path=/story/components-breadcrumb--default

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
In progress, Topics and Countries pushed to be checked on mac VoiceOver

Still some cleaning up to do (some unused attributes), but left some commented out logic if we want to test another approach
https://github.com/eea/volto-eea-design-system/pull/309/commits/d816e7ab9cdf2f202ab994201c16241cfb26c33a 
HeaderMenuPopUp.js Line:15 has an example with testing flex & wrap for list items, but keeping the alphabetical oder vertical. Will be removed later if we are ok with adding inline columns (Line:50)

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
