### PR TITLE
Refactor docusaurus

### PR DESCRIPTION
**Pull request by g-stamatis**
https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-180/12/volto-eea-design-system/

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by ichim-david** [comment]
@g-stamatis we are missing body color, link colors (current, active, visited, hover)
https://ci.eionet.europa.eu/job/volto-addons/job/volto-eea-design-system/job/PR-180/12/volto-eea-design-system/docs/webdev/Guidelines/colours/

**Pull request merged**
