### PR TITLE
Side menu & in page navigation

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/150880

https://62713c57bcbdf4004a3d99b8-prldyrekyw.chromatic.com/?path=/story/components-navigation-portlet--default

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — CHANGES_REQUESTED** [review]
@tarantilis @g-stamatis I don't like that this pull request adds markup that is not available in the normal navigation component.
Ex: 
UI fitted divider tertiary
We will not modify the stock component to add these dividers, you will need to
add them using CSS instead, I suggest using an mixin to simply inherit the CSS without rewriting what is given by these 4 classes

**Comment by g-stamatis** [comment]
@eea-jenkins build docusaurus

**Comment by demarant** [comment]
@tarantilis @g-stamatis
Sorry for this late feedback, I thought the design was already final and accepted, apparently there is more small adjustments to be done

below a feedback I received from the EEA Designer (Gaia), could you please address these comments below, thanks

[19/08, 15:09] Gaia Russo
In general is nice. I think we can avoid the vertical line, and use the padding to separate it from the main column. We have already several lines in the page (Highlight text, tabs, separators) and it could become messy with another one. The lines between the labels could be grey, but if you prefer blue is also fine

**Comment by ichim-david** [comment]
@tarantilis @g-stamatis I will accept the current work since it has a round of feedback changed.
We will try these changes on an actual component and add new issues for another pull request when
done

**Pull request merged**
