### PR TITLE
[ACCESSIBILITY 2.1.1.1] Common elements - Search input icon

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/254316

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by valentinab25** [comment]
@eea-jenkins build storybook

**Comment by valentinab25** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
