### PR TITLE
[Homepage] Hero

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/149926

https://62713c57bcbdf4004a3d99b8-gfluivobtm.chromatic.com/?path=/story/components-hero--default

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Comment by g-stamatis** [comment]
@ichim-david This PR also contains headings size updates.

**Comment by g-stamatis** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
