### PR TITLE
[Accessibility] - Accordion

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/161350

Accordion updated with box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/components-accordion--default

Mega menu updated with box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/layout-header--default

Footer links box-shadow
https://62713c57bcbdf4004a3d99b8-rtsfxcxjle.chromatic.com/?path=/story/layout-footer--default

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Pull request merged**
