### PR TITLE
[R2] Docusaurus documentation / Design tokens [PARTIAL] 2/2

### PR DESCRIPTION
**Pull request by g-stamatis**
https://taskman.eionet.europa.eu/issues/148554

Design tokens for:
- Shadows
- Borders
- Index

### CODE REVIEW

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Comment by g-stamatis** [comment]
@eea-jenkins build all

**Review by ichim-david — APPROVED** [review]
I'm going to approve these so that we have the token files when we have new components
that could make use of tokens.
We will probably change the values in the process of constructing these new components

**Pull request merged**
