### PR TITLE
[Accessibility] EEA Design system components keyboard and screen reader optimization

### PR DESCRIPTION
**Pull request by tarantilis**
https://taskman.eionet.europa.eu/issues/250633

https://62713c57bcbdf4004a3d99b8-dtdmrqsvca.chromatic.com/

### CODE REVIEW

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by tarantilis** [comment]
@eea-jenkins build storybook

**Comment by ichim-david** [comment]
@eea-jenkins build storybook

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
